# Generated by Django 3.1.7 on 2021-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0004_project_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
