# Generated by Django 3.1.7 on 2021-03-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0005_auto_20210329_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default='Fill this in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='Fill this in', max_length=280),
            preserve_default=False,
        ),
    ]
