# Generated by Django 3.1.7 on 2021-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0007_remove_project_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default='This is my personal fpw website, above you will see all of the technology I used to create this site. This site was originally used as a school project, however I found I had put a lot of work into it so rather than start a new site I made the decision to continue building off of what I had already. The site still has a lot of updates I have planned and will continue to be adjusted throughout my career. If you would like to follow the project or just look at the code check out the GitHub link above.'),
            preserve_default=False,
        ),
    ]
